name: Profile automations

on:
  schedule:
    - cron: '0 1,13 * * *'   # every 12 hours (UTC)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: profile-automations
  cancel-in-progress: false

jobs:
  metrics:
    name: Build metrics.svg
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dadadave80
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Lagos

          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics.svg

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 12
          plugin_languages_sections: most-used, recently-used
          plugin_achievements: yes
          plugin_stargazers: yes

          plugin_repositories: yes
          plugin_repositories_pinned: 2
          plugin_gists: yes

          plugin_discussions: yes
          plugin_discussions_categories_limit: 8

          plugin_topics: yes
          plugin_topics_limit: 10
          plugin_topics_mode: icons

          # === Social / external plugins ===

          # StackOverflow
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 6909285
          plugin_stackoverflow_sections: answers, questions, top_tags
          plugin_stackoverflow_limit: 5

          # Recent posts plugin (another way of showing posts)
          plugin_posts: yes
          plugin_posts_source: dev.to, medium, hashnode
          plugin_posts_descriptions: yes
          plugin_posts_covers: no
          plugin_posts_limit: 4
